import Head from 'next/head';
import { Fonts } from './fonts';
import './globals.css';
import { Inter } from 'next/font/google';
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Fonts />
      <body className={inter.className}>
        {children}
        <Script
          src="https://code.createjs.com/1.0.0/createjs.min.js"
          strategy='beforeInteractive'
        />
      </body>
    </html>
  )
}
